version: '3'
services:
  web:
    image: allegro/ralph:latest
    restart: always
    ports:
      - "8000"
    volumes:
      - ralph_media:/var/local/ralph/media
      - ralph_static:/usr/share/ralph/static
    links:
      - db
      - redis
      - nginx
    environment:
        DATABASE_NAME: YOUR_DATABASE_NAME
        DATABASE_USER: YOUR_DATABASE_USER
        DATABASE_PASSWORD: YOUR_DATABASE_PASSWORD
        DATABASE_HOST: db
        REDIS_HOST: redis
        REDIS_PASSWORD: "YOUR_REDIS_PASSWORD"
        REDIS_PORT: 6379
        REDIS_DB: 0

  nginx:
    image: allegro/ralph-static-nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ralph_media:/opt/media
      - YOUR_CERTIFICATE_PATH:/etc/nginx/ssl
      - YOUR_NGINX_CONFIG_PATH:/etc/nginx/conf.d/default.conf
    command: /bin/bash -c "nginx -g 'daemon off;'"
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: YOUR_MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
      MYSQL_USER: YOUR_MYSQL_USER
      MYSQL_PASSWORD: YOUR_MYSQL_PASSWORD
    volumes:
      - ralph_dbdata:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:3.0
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass YOUR_REDIS_PASSWORD'  

  inkpy:
    image: allegro/inkpy:latest
    restart: always
    links:
      - redis:redis
    environment:
        REDIS_HOST: redis
        REDIS_PASSWORD: "YOUR_REDIS_PASSWORD"
        REDIS_PORT: 6379
        REDIS_DB: 0

volumes:
  redis_data:
  ralph_dbdata:
  ralph_media:
  ralph_static:
